baseURL = 'https://tnalpgge.github.io/technically-nightshade'
languageCode = 'en-us'
title = 'Technically Nightshade'
theme = 'black-and-light'
ignorefiles = ['~$']
pygmentsstyle = "bw"
pygmentscodefences = false

[params]
sitename = "Technically Nightshade"
